# Generated by Django 2.0.3 on 2018-03-14 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('apartment_cost', models.IntegerField()),
                ('hotel_cost', models.IntegerField()),
                ('deposit_value', models.IntegerField()),
                ('group_number', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance_type', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_apartments', models.IntegerField()),
                ('one_apartments', models.IntegerField()),
                ('two_apartments', models.IntegerField()),
                ('three_apartments', models.IntegerField()),
                ('four_apartments', models.IntegerField()),
                ('five_apartments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('players_amount', models.IntegerField()),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('jailed', models.IntegerField()),
                ('position', models.IntegerField()),
                ('active', models.BooleanField()),
                ('jail_free_card', models.BooleanField()),
                ('move', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildings', models.IntegerField()),
                ('deposited', models.BooleanField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Card')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='charge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Charge'),
        ),
    ]
