# Generated by Django 2.0.3 on 2018-03-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='charge_id',
            new_name='charge',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='host_id',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='player_id',
            new_name='player',
        ),
    ]
