# Generated by Django 2.0.3 on 2018-04-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180322_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
