# Generated by Django 2.0.3 on 2018-04-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='buildings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='deposited',
            field=models.BooleanField(default=False),
        ),
    ]
