# Generated by Django 2.0.3 on 2018-04-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180418_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
