# Generated by Django 2.0.3 on 2018-05-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180418_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
    ]
