# Generated by Django 2.0.3 on 2018-05-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_active'),
        ('game', '0005_property_selling_price'),
    ]

    operations = [
    ]
